Repository swarooppatilx/scruter, pull requests merged in 2024-10, with the labels that each got.

#24 Add some style and contribution section in docs
  README.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#28 Fixed #27 : Automated Greeting Workflow
  .github/workflows/greetings.yml
Labels: gssoc-ext, level1, hacktoberfest-accepted

#31 fixes the search bar
  .github/workflows/greetings.yml
Labels: gssoc-ext, level1, hacktoberfest-accepted

#29 Added the footer section
  views/index.ejs
Labels: gssoc-ext, level1, hacktoberfest-accepted

#41 twitter logo change in to x
  views/index.ejs
Labels: good first issue, gssoc-ext, level1, hacktoberfest-accepted

#54 changed card ui
  views/display.ejs
Labels: gssoc-ext, level1, hacktoberfest-accepted

#58 Enhanced the ui/ux of the button of signup signin forms
  package-lock.json
  views/auth.ejs
Labels: gssoc-ext, level1, hacktoberfest-accepted

#59 Increased the sign-in button height and changed the border radius
  public/formstyle.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#74 Enhancing Readme.md
  README.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#65 footer-updated
  views/index.ejs
Labels: gssoc-ext, level1, hacktoberfest-accepted

#60 enhanced ui
  public/formstyle.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#55 Improved the navbar's visual design
  views/partials/navbar.ejs
Labels: gssoc-ext, level1, hacktoberfest-accepted

#97 Footer Partial Added
  views/display.ejs
  views/index.ejs
  views/partials/footer.ejs
Labels: gssoc-ext, level1, hacktoberfest-accepted

#132 Designed and added hover animation to information section
  views/index.ejs
Labels: gssoc-ext, level1, hacktoberfest-accepted

#128 feat: add security policy and supported versions to security.md
  SECURITY.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#124 Fixed Login page UI is messed up issue ! #110
  uploads/index.html
  views/auth.ejs
Labels: gssoc-ext, level1, hacktoberfest-accepted

#82 Issue and PR templates added
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/auto-label.yml
Labels: gssoc-ext, level1, hacktoberfest-accepted

#146 Adding a PR/MR Template
  PULL_REQUEST_TEMPLATE.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#149 link hower effect added
  views/partials/footer.ejs
Labels: gssoc-ext, level1, hacktoberfest-accepted

#153 Fixed login, signup page and added scroll to top button
  views/auth.ejs
  views/index.ejs
Labels: gssoc-ext, level1, hacktoberfest-accepted

#160 add sign-up(register) button
  package-lock.json
  package.json
  views/partials/bottom_nav.ejs
  views/partials/navbar.ejs
Labels: gssoc-ext, level1, hacktoberfest-accepted

#182 added terms and privacy content
  app.js
  views/privacy-policy.ejs
  views/terms.ejs
Labels: level2

#184 modified the nav layout
  views/partials/navbar.ejs
Labels: gssoc-ext, level1, hacktoberfest-accepted

#187 Home page icon
  views/partials/navbar.ejs
Labels: gssoc-ext, level1, hacktoberfest-accepted

#213 fix dark mode
  public/css/global.css
Labels: gssoc-ext, level1, hacktoberfest-accepted

#194 forms fixed . #141 solved
  package-lock.json
  views/auth.ejs
Labels: gssoc-ext, level2, hacktoberfest-accepted

#204 Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr-checker.yaml
Labels: gssoc-ext, level2, hacktoberfest-accepted

#215 header dark mode visibility fixed
  views/partials/navbar.ejs
Labels: gssoc-ext, level1, hacktoberfest-accepted

#217 Issue Fixed
  views/partials/navbar.ejs
Labels: gssoc-ext, level2, hacktoberfest-accepted

#201 Improved Navigation Bar UI
  public/avatar.jpg
  views/partials/bottom_nav.ejs
  views/partials/navbar.ejs
Labels: gssoc-ext, level3, hacktoberfest-accepted

#205 About Us Page Updated
  views/about.ejs
Labels: gssoc-ext, level2, hacktoberfest-accepted

#206 Update Terms and Conditions Page
  views/terms.ejs
Labels: gssoc-ext, level2, hacktoberfest-accepted

#214 refactor: simplify form validation logic
  public/js/client-validation.js
Labels: level2

#229 Fix Scrolling Functionality on Signup Page
  views/auth.ejs
Labels: gssoc-ext, level1, hacktoberfest-accepted

#230 added remember me interface
  views/auth.ejs
Labels: gssoc-ext, level2, hacktoberfest-accepted

#233 Add crousel to the header of the landing page
  public/2.png
  public/3.png
  views/index.ejs
Labels: gssoc-ext, level2, hacktoberfest-accepted

#239 Added Multi-Lingual Support to Scruter
  views/partials/footer.ejs
  views/partials/navbar.ejs
Labels: gssoc-ext, level3, hacktoberfest-accepted

#241 Github actions for more connectivity!
  .github/workflows/greetings.yml
  .github/workflows/issue_close_open.yml
  .github/workflows/pr_merge.yaml
  .github/workflows/pr_raise.yml
Labels: gssoc-ext, level2, hacktoberfest-accepted

#252 added dark theme visibility to options in housing,food,...
  public/css/global.css
Labels: gssoc-ext, level2, hacktoberfest-accepted

#263 UI Improvements and Theme Toggle Feature on Privacy Policy page
  views/privacy-policy.ejs
Labels: gssoc-ext, level2, hacktoberfest-accepted

#271 added terms and conditions
  app.js
  views/partials/footer.ejs
  views/terms-page.ejs
Labels: gssoc-ext, level3, hacktoberfest-accepted

#272 Update README.md
  README.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#285 added help center page
  app.js
  views/help.ejs
Labels: gssoc-ext, level3, hacktoberfest-accepted

#307 initialised next app and added homepage
  scruter-nextjs/.eslintrc.json
  scruter-nextjs/.gitignore
  scruter-nextjs/README.md
  scruter-nextjs/app/(routes)/page.tsx
  scruter-nextjs/app/favicon.ico
  scruter-nextjs/app/fonts/GeistMonoVF.woff
  scruter-nextjs/app/fonts/GeistVF.woff
  scruter-nextjs/app/globals.css
  scruter-nextjs/app/layout.tsx
  scruter-nextjs/components.json
  scruter-nextjs/components/NavBars&Footers/footer.tsx
  scruter-nextjs/components/NavBars&Footers/main-nav.tsx
  scruter-nextjs/components/NavBars&Footers/navbar-actions.tsx
  scruter-nextjs/components/NavBars&Footers/navbar.tsx
  scruter-nextjs/components/heroCards.tsx
  scruter-nextjs/components/heroCarousal.tsx
  scruter-nextjs/components/ui/button.tsx
  scruter-nextjs/components/ui/card.tsx
  scruter-nextjs/components/ui/carousel.tsx
  scruter-nextjs/components/ui/container.tsx
  scruter-nextjs/components/ui/dropdown-menu.tsx
  scruter-nextjs/components/ui/input.tsx
  scruter-nextjs/components/ui/pageContainer.tsx
  scruter-nextjs/lib/utils.ts
  scruter-nextjs/next.config.ts
  scruter-nextjs/package-lock.json
  scruter-nextjs/package.json
  scruter-nextjs/postcss.config.mjs
  scruter-nextjs/public/chatting.svg
  scruter-nextjs/public/file.svg
  scruter-nextjs/public/globe.svg
  scruter-nextjs/public/next.svg
  scruter-nextjs/public/search.svg
  scruter-nextjs/public/shop.svg
  scruter-nextjs/public/vercel.svg
  scruter-nextjs/public/window.svg
  scruter-nextjs/tailwind.config.ts
  scruter-nextjs/tsconfig.json
  scruter-nextjs/utils/utils.ts
Labels: gssoc-ext, level3, hacktoberfest-accepted

#304 Adding a Support Page
  app.js
  views/support.ejs
Labels: gssoc-ext, level2, hacktoberfest-accepted

#302 Updated hamburger icon visibility in dark mode
  views/partials/navbar.ejs
Labels: gssoc-ext, level1, hacktoberfest-accepted

#294 Implemented Edit Post Feature
  app.js
  views/display.ejs
  views/edit.ejs
  views/form.ejs
Labels: gssoc-ext, level3, hacktoberfest-accepted

#286 Update contributors.ejs added scroll to top button
  views/contributors.ejs
Labels: gssoc-ext, level1, hacktoberfest-accepted

#317 Fixes the Issues raised in PR
  .env.example
  public/css/global.css
  views/index.ejs
  views/partials/footer.ejs
  views/privacy-policy.ejs
Labels: gssoc-ext, level2, hacktoberfest-accepted

#313 Added button of Buy Now on cards
  views/display.ejs
Labels: gssoc-ext, level2, hacktoberfest-accepted

#312 Update README.md with table of contents
  README.md
Labels: gssoc-ext, level1, hacktoberfest-accepted

#330 animated curser added
  scruter-nextjs/app/(routes)/page.tsx
  scruter-nextjs/components/ui/CustomCursor.jsx
  scruter-nextjs/package-lock.json
  scruter-nextjs/package.json
Labels: gssoc-ext, level2, hacktoberfest-accepted

#331 Implement Issue Reminder Workflow🚀
  .github/workflows/issue-reminder.yml
Labels: gssoc-ext, level2, hacktoberfest-accepted

#333 infrastructure components (email, database, and authentication) needed for the project's smooth operation.
  scruter-nextjs/lib/auth.ts
  scruter-nextjs/lib/nodemailerConfig.ts
  scruter-nextjs/lib/prismadb.ts
  scruter-nextjs/lib/sendEmail.ts
  scruter-nextjs/package-lock.json
  scruter-nextjs/package.json
  scruter-nextjs/prisma/schema.prisma
  scruter-nextjs/types/next-auth.d.ts
Labels: gssoc-ext, level3, hacktoberfest-accepted

#332 Added Sort By Price Functionality | Issue #318
  app.js
  views/partials/searchbar.ejs
Labels: gssoc-ext, level2, hacktoberfest-accepted

#336 Added Sort By Price Functionality in Market | Issue #321
  app.js
Labels: gssoc-ext, level2, hacktoberfest-accepted

#334 Added Sort By Price Functionality in Food Page | Issue #320
  app.js
  database.js
Labels: gssoc-ext, level2, hacktoberfest-accepted

#337 Added BackToTop Button in All the Page | Issue #319
  views/display.ejs
  views/index.ejs
Labels: gssoc-ext, level2, hacktoberfest-accepted

#351 CREATE DOCUMENTATION TEMPLATE
  .github/ISSUE_TEMPLATE/Documentation.yml
Labels: gssoc-ext, level1, hacktoberfest-accepted

#359 CREATE A CUSTOM ISSUE TEMPLATE
  .github/ISSUE_TEMPLATE/custom.yml
Labels: gssoc-ext, level2, hacktoberfest-accepted

#338 Completely Redesign the T&C Page | Issue #323
  views/terms-page.ejs
Labels: gssoc-ext, level2, hacktoberfest-accepted

#346 Seller signup
  scruter-nextjs/actions/seller/signup-action.tsx
  scruter-nextjs/app/(routes)/auth/components/otp-form.tsx
  scruter-nextjs/app/(routes)/auth/components/signup-form.tsx
  scruter-nextjs/app/(routes)/auth/seller/signup/page.tsx
  scruter-nextjs/app/(routes)/auth/user/signup/page.tsx
  scruter-nextjs/app/(routes)/layout.tsx
  scruter-nextjs/app/(routes)/page.tsx
  scruter-nextjs/app/api/auth/[...nextauth]/route.ts
  scruter-nextjs/app/api/auth/seller/signup/route.ts
  scruter-nextjs/components/NavBars&Footers/main-nav.tsx
  scruter-nextjs/components/NavBars&Footers/navbar-actions.tsx
  scruter-nextjs/components/NavBars&Footers/navbar.tsx
  scruter-nextjs/components/ui/container.tsx
  scruter-nextjs/components/ui/form.tsx
  scruter-nextjs/components/ui/icons.tsx
  scruter-nextjs/components/ui/input-otp.tsx
  scruter-nextjs/components/ui/label.tsx
  scruter-nextjs/lib/auth.ts
  scruter-nextjs/package-lock.json
  scruter-nextjs/package.json
  scruter-nextjs/prisma/schema.prisma
  scruter-nextjs/public/signupPattern.svg
  scruter-nextjs/public/userAuth.svg
  scruter-nextjs/public/userAuth1.svg
  scruter-nextjs/tailwind.config.ts
Labels: gssoc-ext, level3, hacktoberfest-accepted

#378 enhanced scroll to top
  views/index.ejs
Labels: gssoc-ext, level2, hacktoberfest-accepted

#380 added content to contact us page
  app.js
  views/contact.ejs
  views/partials/footer.ejs
Labels: gssoc-ext, level3, hacktoberfest-accepted
